Use current work dir as base & Provide a success counter.

diff --git a/git-all b/git-all
--- a/git-all
+++ b/git-all
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-PROJECTS_DIR=~/projects
+BASEDIR=$PWD
+COUNTER=0
 
 # Abort immediately on errors
 set -e
@@ -9,12 +10,16 @@ function git_fetch {
 	echo ''
 	echo --- $1
 	cd $1
+	let COUNTER=COUNTER+1
 	git fetch --all	
 	if [ -e .git/svn/refs/remotes ]; then
 		echo Fetching SVN commits...
 		git svn fetch --log-window-size=10000
+		# The follwing command may fail. This is ok.
+		set +e
 		#echo Trying a 'git svn rebase -l'
 		git svn rebase -l 2> /dev/null
+		set -e
 	fi
 }
 
@@ -28,18 +33,22 @@ fi
 
 case $COMMAND in
 fetch)
-	for gitdir in $( find $PROJECTS_DIR -maxdepth 1 -name '*.git' -type d ); do
+	for gitdir in $( find $BASEDIR -maxdepth 1 -name '*.git' -type d ); do
     	git_fetch $gitdir
 	done
 	;;
 *)
-	for gitdir in $( find $PROJECTS_DIR -maxdepth 1 -name '*.git' -type d ); do
+	for gitdir in $( find $BASEDIR -maxdepth 1 -name '*.git' -type d ); do
 		echo ''
 		echo --- $gitdir
     	cd $gitdir
-    	echo Executing: git $COMMAND $ARGS
+  		let COUNTER=COUNTER+1
+    	#echo Executing: git $COMMAND $ARGS
     	git $COMMAND $ARGS
 	done
 	;;
 esac
+
+echo 
+echo Success: $COUNTER Git directories processed with "git $COMMAND $ARGS"
 
